# GitHub Pages configuration
title: Isaac Souza - Front-End Developer
description: Desenvolvedor Front-End apaixonado por criar experiências digitais modernas
author: Isaac Souza
email: souza-sjc@hotmail.com

# Jekyll configuration
baseurl: "/Isaac-Exon"
url: "https://isaac-souza-santos.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-primer

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .github/
  - _layouts/
  - _config.yml

# Include files
include:
  - _redirects
  - _headers
  - google6ea14f55b40fafcd.html
  - app-ads.txt
